FAS/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='FAS'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('fas_home/', views.fas_home, name="fas_home"),
    path('fas_home/create_emp/', views.create_emp, name="create_emp"),
    path('fas_home/start_stop/', views.start_stop_sys, name="start_stop_sys"),
    path('fas_home/create_emp/cap_res/', views.cap_res, name="capture_result"),
    path('records/', views.records, name="records")
]

FAS/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.sessions.models import Session
from django.db.models.signals import pre_delete
from django.dispatch import receiver

class Employee(models.Model):
    emp_name=models.CharField(max_length=100, default="")
    emp_code=models.CharField(max_length=8, default="", unique=True)
    emp_photo=models.BooleanField(default=False)
    emp_encoding=models.BooleanField(default=False)
    
    def __str__ (self):
        return self.emp_code

class Record(models.Model):
    emp_name=models.CharField(max_length=100, default="")
    emp_code=models.CharField(max_length=8, default="")
    attendance_confi=models.FloatField()
    attendance_date=models.DateField()
    attendance_time=models.TimeField()
    remark=models.CharField(max_length=100, default="None")
    def __str__ (self):
        return self.emp_code

FAS/forms.py
from django import forms

class emp_reg(forms.Form):
    emp_code=forms.CharField(label="Employee Code", max_length=8)
    emp_name=forms.CharField(label="Employee Name", max_length=100)
    

FAS/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from .forms import emp_reg
from .face_capture import gen_emp_face
from .encode_face import gen_emp_data
from .create_result import find_emp
from django.db import IntegrityError
from .models import Employee, Record
from datetime import date, time
from datetime import datetime

IS_LIVE=False
def home(request):
    return render(request, 'homepage.html', {})

def fas_home(request):
    return render(request, 'fas_home.html', {"live":IS_LIVE})

def create_emp(request):
    if request.method == 'POST':
        form = emp_reg(request.POST)
        if form.is_valid():
            name=form.cleaned_data['emp_name']
            empid=form.cleaned_data['emp_code']
            employee=Employee()
            employee.emp_name=name
            employee.emp_code=empid
            val=gen_emp_face(name)
            if val:
                employee.emp_photo=True
                employee.save()                
            return render(request, 'cap_res.html', {"complete":val, "name":name})
        
    else:
        form = emp_reg()

    return render(request, 'emp_reg.html', {'form': form})

def cap_res(request):
    if request.method=="POST":
        name=request.POST.get("emp_name")
        employee=Employee.objects.get(emp_name=name)
        encoding=gen_emp_data("FAS/dataset/faces/{}".format(name), name, "FAS/dataset/encodings/")
        if encoding:
            employee.emp_encoding=True
            employee.save()
            return redirect('fas_home')
        else :
            return HttpResponse("Internal Error")
    else:
        return HttpResponse("Wrong Method")

def start_stop_sys(request):
    global IS_LIVE
    if IS_LIVE:
        name, matches=find_emp()
        if name :
            employee=Employee.objects.get(emp_name=name)
            ent=Record()
            ent.emp_name=employee.emp_name
            ent.emp_code=employee.emp_code
            per=(float(matches)/26) *100
            ent.attendance_confi=per
            ent.attendance_date=date.today()
            now=datetime.now()
            Time=time(now.hour, now.minute, now.second)
            ent.attendance_time=Time
            if per < 50 :
                ent.remark="Manual Verfication required"
            ent.save()
        elif name=="Invalid Image":
            return HttpResponse("Invalid Image: Retake Picture")
        else :
            return HttpResponse("Intrusion")
    IS_LIVE = not IS_LIVE
    return redirect('fas_home')

def records(request):
    all_records=Record.objects.all().values()
    record_list=list(all_records)
    return JsonResponse(record_list, safe=False)

FAS/templates/base.html
{% load static %}
<html>
<head>
<title>FAS</title>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
</head>
<body>
    <div class="content">
        <div class="row">
            <div class="col-md-8">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

FAS/templates/cap_res.html
{% extends 'base.html' %}
{% block content %}
<h1>
    Face Database Creation for {{name}}
    {% if complete %} 
    Completed 
    {% else %} 
    Not Completed 
    {% endif %}
</h1>

{% if complete %}
<h2> Proceed to create the face encoding</h2>
<form action="/fas_home/create_emp/cap_res/" method="post">
    {% csrf_token %}
    <input id="id_emp_name" type="hidden" name="emp_name" value={{name}} method="POST">
    <input type="submit" value="Start Encoding">
</form>
{% else %}
<h2> Please Recapture the face</h2>
<form action="/fas_home/create_emp/" method="POST">
    {% csrf_token %}
    <input type="submit" value="Recapture">
</form>
{% endif %}

{% endblock %}

FAS/templates/emp_reg.html
<form action="/fas_home/create_emp/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Start Capturing">
</form>

FAS/templates/fas_home.html
{% extends 'base.html' %}
{% block content %}
    <ul>
        <li><a href="/fas_home/create_emp/">Add Employee</a></li>
        <li><a href="/records/">Check Attendance Record</a></li>
        <li><a href="/fas_home/start_stop/">{% if live %}Stop{% else %} Start {% endif %}</a></li>
    </ul>
{% endblock %}

FAS/templates/homepage.html
{% extends 'base.html' %}
{% block content %}
    <h1>FAS</h1>
    <a href="fas_home/">Click here</a>
{% endblock %}